template:
  - sensor:
      - name: "Pump state"
        state: >-
          {% if is_state('switch.pump', 'on') %}
            {% if is_state('switch.turbo', 'on') %}
              high
            {% else %}
              low
            {% endif %}
          {% else %}
            None
          {% endif %}
      - name: "Remain cycles"
        state: >-
          {% set recirc_hours = state_attr('input_datetime.recirculation', 'hour') | int(0) %}
          {% set recirc_minutes = state_attr('input_datetime.recirculation', 'minute') | int(0) %}
          {% set recirc_total = recirc_hours + (recirc_minutes / 60) %}
          {% set recirc_total = recirc_total if recirc_total > 0 else 1 %}
          {% set low = states('sensor.cummulated_flow_low') | float(0) %}
          {% set high = states('sensor.cummulated_flow_high') | float(0) %}
          {% set cycles = states('input_number.notify_cycles') | float(0) %}
          {{ (cycles - (low + high * 5) / recirc_total) | round(1) }}

sensor:
  - platform: history_stats
    name: cummulated_flow_low
    entity_id: sensor.pump_state
    state: 'low'
    type: time
    start: "{{ state_attr('input_datetime.cummulated_flow_start','timestamp') }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: cummulated_flow_high
    entity_id: sensor.pump_state
    state: 'high'
    type: time
    start: "{{ state_attr('input_datetime.cummulated_flow_start','timestamp') }}"
    end: "{{ now() }}"

input_datetime:
  cummulated_flow_start:
    name: Cummulated Flow Start
    has_date: true
    has_time: true
    icon: mdi:timer

input_number:
  notify_cycles:
    name: Notify cycles flow
    icon: mdi:timer
    min: 0
    max: 100
    step: 5

automation:
- alias: notify_cummulated_flow
  id: '1559049859380'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.remain_cycles
    below: 1
  condition:
  - condition: numeric_state
    entity_id: input_number.notify_cycles
    above: 0
  action:
  - service: persistent_notification.create
    data:
      title: "Filtration: {{ states('input_number.notify_cycles') | int(0) }} cycles atteints!!!"
      message: "Vitesse basse: {{ states('sensor.cummulated_flow_low') }}{{ '\n' }}Vitesse haute: {{ states('sensor.cummulated_flow_high') }}{{ '\n' }}@{{ now().strftime('%H:%M') }}[{{ now().day }}/{{ now().month }}]"
      notification_id: "pool_flow_cycles"

- alias: reset_cummulated_flow_start
  id: '1559293506609'
  trigger: []
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      entity_id: input_datetime.cummulated_flow_start
      date: "{{now().timestamp()|timestamp_custom('%Y-%m-%d', True)}}"
      time: "{{now().timestamp()|timestamp_custom('%H:%M:%S', True)}}"


