input_boolean:
  notify_seasson:
    name: "Alertes changement de saison"
    icon: mdi:comment-alert


automation:

- alias: winter_session
  id: '1559049956784'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: input_number.cycle
    below: 240
    for:
      hours: 121
  condition:
  - condition: state
    entity_id: input_boolean.notify_seasson
    state: 'on'
  action:
  - service: persistent_notification.create
    data:
      title: "L'hiver arrive !"
      message: "@{{ now().strftime('%H:%M') }}[{{ now().day }}/{{ now().month }}]"
      notification_id: "pool_winter_session"

- alias: summer_session
  id: '1559049956785'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: input_number.cycle
    above: 240
    for:
      hours: 121
  condition:
  - condition: state
    entity_id: input_boolean.notify_seasson
    state: 'on'
  action:
  - service: persistent_notification.create
    data:
      title: "L'été est là !"
      message: "@{{ now().strftime('%H:%M') }}[{{ now().day }}/{{ now().month }}]"
      notification_id: "pool_summer_session"

